### ISSUE TITLE
License error

### ISSUE THREAD

**Issue by davenewza** [postsharp/PostSharp.Dnx#3]
After registering for the free PostSharp Express, I still get the following licensing error upon building:

 > License error. MyProject.dll uses non-licensed features (Portable Class Library Support). Please visit  > http://www.postsharp.net/purchase to acquire a license of PostSharp. The installed user license is: "..."

I am using Visual Studio 2015 and DNX projects.

**Comment by gfraiteur** [comment]
We haven't looked at the licensing for .NET Core yet. I suggest you apply for an open-source license at: https://www.postsharp.net/purchase/discounts

**Comment by davenewza** [comment]
@gfraiteur We are not using .NET Core.  I'm referencing `PostSharp.Dnx` in a DNX project (targeting dnx451) and attempting to create my own `OnMethodBoundaryAspect` but I cannot get this project to build due to the above error.

**Comment by gfraiteur** [comment]
I understand. But we are planning to work on licensing in 4.3 so if getting a free OSS license would fix the problem for you, we would save some time addressing this issue in 4.2. That's why I'm proposing you this license.

**Comment by davenewza** [comment]
Thanks, I have applied.

**Comment by gfraiteur** [comment]
Okay, the license is on the way. Write if it does not come within 15 min (or check your spambox).
